# coding: utf-8

"""
    Arbitrage Watcher RESTful API

    Provides the set of endpoints to manage arbitrage watcher service.

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.watcher_api import WatcherApi


class TestWatcherApi(unittest.TestCase):
    """ WatcherApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.watcher_api.WatcherApi()

    def tearDown(self):
        pass

    def test_api_watcher_markets(self):
        """
        Test case for api_watcher_markets

        Returns a list of markets available for watching
        """
        pass

    def test_api_watcher_start(self):
        """
        Test case for api_watcher_start

        Start the watching process
        """
        pass

    def test_api_watcher_status(self):
        """
        Test case for api_watcher_status

        Returns a status of the watcher
        """
        pass

    def test_api_watcher_stop(self):
        """
        Test case for api_watcher_stop

        Stop the watcher process
        """
        pass


if __name__ == '__main__':
    unittest.main()
