# coding: utf-8

"""
    Arbitrage Watcher RESTful API

    Provides the set of endpoints to manage arbitrage watcher service.

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.inline_response_200_1_current_parameters import InlineResponse2001CurrentParameters


class TestInlineResponse2001CurrentParameters(unittest.TestCase):
    """ InlineResponse2001CurrentParameters unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2001CurrentParameters(self):
        """
        Test InlineResponse2001CurrentParameters
        """
        model = swagger_client.models.inline_response_200_1_current_parameters.InlineResponse2001CurrentParameters()


if __name__ == '__main__':
    unittest.main()
