# coding: utf-8

"""
    Arbitrage Watcher RESTful API

    Provides the set of endpoints to manage arbitrage watcher service.

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.watcher_config import WatcherConfig


class TestWatcherConfig(unittest.TestCase):
    """ WatcherConfig unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWatcherConfig(self):
        """
        Test WatcherConfig
        """
        model = swagger_client.models.watcher_config.WatcherConfig()


if __name__ == '__main__':
    unittest.main()
