# coding: utf-8

"""
    Arbitrage Watcher RESTful API

    Provides the set of endpoints to manage arbitrage watcher service.

    OpenAPI spec version: 0.1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into sdk package
from .models.application_config import ApplicationConfig
from .models.inline_response_200 import InlineResponse200
from .models.inline_response_200_1 import InlineResponse2001
from .models.inline_response_200_1_current_parameters import InlineResponse2001CurrentParameters
from .models.inline_response_200_2 import InlineResponse2002
from .models.inline_response_400 import InlineResponse400
from .models.parameters import Parameters
from .models.watcher_config import WatcherConfig

# import apis into sdk package
from .apis.watcher_api import WatcherApi

# import ApiClient
from .api_client import ApiClient

from .configuration import Configuration

configuration = Configuration()
